# Generated by Django 5.1.4 on 2024-12-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
